version: '3'
services:
    python:
        build: .
        container_name: e-paperfect
        volumes:
            - ./script:/src/script
            - ./assets:/src/assets
        command: python3 /src/script/main.py
        environment:
            - TZ=Europe/Paris
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "3"
networks:
    default:
        name: main
        external: true
